# You can use this file to create a conda environment for the genome-annotation pipeline:
#   conda env create -f genome-annotation-conda.yml
name: esga-1.2
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
 - parallel
 - samtools
 - bioconda::hisat2=2.2.1
 - cdbtools
 - exonerate=2.4.0 
 - evidencemodeler=1.1.1
 - gffread=0.11.7
 - pasa=2.4.1
 - bioconda::perl-uri=1.76
 - bioconda::genomethreader=1.7.1
