# You can use this file to create a conda environment for the genome-annotation pipeline:
#   conda env create -f genome-annotation-conda.yml
name: esga-1.1
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
 - parallel
 - samtools
 - repeatmodeler=1.0.11
 - repeatmasker=4.0.7
 - cdbtools
 - exonerate=2.4.0 
 - hisat2=2.2.1
 - evidencemodeler=1.1.1
 - minimap2=2.17
 - gffread=0.11.7
 - pasa=2.4.1
 - gaas
 - bioconda::perl-uri=1.76
