genome: ""
proteins: false
proteins_targeted: false
transcripts: false
rm_lib: false
rm_species: false
reads: false
references: false
aug_species: "human"
aug_options: ""
spaln_taxon: "Tetrapod"
spaln_q: 5
utr: false
ncrna: false
trinity: false
pasa: false
evm: false
nevm: 10
nproteins: 200
npart_size: 200000000
max_intron_size: 50000
min_contig_size: 5000
singleEnd: false
rnaseq_stranded: false
email: false
