genome: ""
proteins: false
proteins_targeted: false
transcripts: false
rm_lib: false
rm_species: false
reads: false
aug_species: "human"
aug_options: ""
utr: false
trinity: false
pasa: false
evm: false
nevm: 10
nblast: 200
nexonerate: 400
npart_size: 200000000
ax_intron_size: 50000
min_contig_size: 5000
singleEnd: false
rnaseq_stranded: false
email: false
